name: Deploy a Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código
      uses: actions/checkout@v4

    # 1. Configurar el entorno de Node.js
    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '25'
        cache: 'npm'

    # 2. Instalar las dependencias exactas
    - name: Instalar dependencias
      run: npm ci

    # 3. Generar el cliente de Prisma
    - name: Generar Prisma Client
      run: npx prisma generate

    # 4. Compilar el proyecto inyectando las variables requeridas
    - name: Construir el proyecto
      env:
        AZURE_STORAGE_CONNECTION_STRING: "UseDevelopmentStorage=true"
        COSMOS_DB_ENDPOINT: "https://localhost:8081"
        COSMOS_DB_KEY: "dummy-key"
        DATABASE_URL: "postgresql://user:password@localhost:5432/db"
      run: npm run build

    # 5. Desplegar en Azure App Service
    - name: Desplegar en Azure App Service
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'appservicecentineladev'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '.'